customhost = "employee.coghw13fheqo.us-east-2.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "addemployee"
customregion = "us-east-2"
